import { Questrial } from 'next/font/google';

import '@fonts/css/switzer.css';
import './globals.css';

import '@fonts/font-awesome.min.css';

import '@css/plugins/bootstrap-grid.css';

import '@css/plugins/swiper.min.css';

import '@css/plugins/magnific-popup.css';

import '@css/style.css';
import Preloader from '@/commons/Preloader';
import { getLocale, getMessages } from 'next-intl/server';
import { NextIntlClientProvider } from 'next-intl';

const secondary_font = Questrial({
	weight: ['400'],
	style: ['normal'],
	subsets: ['latin'],
	variable: '--font-secondary',
	display: 'swap',
	adjustFontFallback: false,
});

export const metadata = {
	title: 'Plax - Finance & Fintech React NextJS Template',
	description: 'Generated by create next app',
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
	const locale = await getLocale();
	const messages = await getMessages();

	return (
		<html lang={locale} className={`${secondary_font.variable}`}>
			<body>
				<NextIntlClientProvider messages={messages}>
					<Preloader />
					{children}
				</NextIntlClientProvider>
			</body>
		</html>
	);
}
